extends: default
rules:
  line-length:
    max: 200  # Set a more reasonable limit instead of disable
  comments: disable
  comments-indentation: disable
  truthy: disable
  trailing-spaces: disable
  new-line-at-end-of-file: disable
  document-start: disable
  empty-lines: disable
  brackets: disable
  braces: disable
  indentation: disable